// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Weapon struct {
	InstanceID string
	Hash       int64
	Name       string
	Type       string
	Power      int64
	Kills      int64
	Level      int64
	Location   string
	UpdatedAt  sql.NullTime
}

type WeaponPerk struct {
	ID          int64
	InstanceID  string
	PerkHash    int64
	PerkName    string
	IsActive    bool
	IsEquipped  bool
	SocketIndex int64
}

type WeaponStat struct {
	InstanceID string
	StatName   string
	Value      int64
}
