// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weapons.sql

package db

import (
	"context"
)

const clearWeaponPerks = `-- name: ClearWeaponPerks :exec
DELETE FROM weapon_perks WHERE instance_id = ?
`

func (q *Queries) ClearWeaponPerks(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, clearWeaponPerks, instanceID)
	return err
}

const clearWeaponStats = `-- name: ClearWeaponStats :exec
DELETE FROM weapon_stats WHERE instance_id = ?
`

func (q *Queries) ClearWeaponStats(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, clearWeaponStats, instanceID)
	return err
}

const getGodRollCandidates = `-- name: GetGodRollCandidates :many
SELECT 
  w.instance_id, w.hash, w.name, w.type, w.power, w.kills, w.level, w.location, w.updated_at FROM weapons w
JOIN weapon_perks p ON w.instance_id = p.instance_id
JOIN weapon_stats s ON w.instance_id = s.instance_id
WHERE p.perk_name = ? AND s.stat_name = 'Range' AND s.value > ?
`

type GetGodRollCandidatesParams struct {
	PerkName string
	Value    int64
}

func (q *Queries) GetGodRollCandidates(ctx context.Context, arg GetGodRollCandidatesParams) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getGodRollCandidates, arg.PerkName, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWeaponPerk = `-- name: InsertWeaponPerk :exec
INSERT INTO weapon_perks (instance_id, perk_hash, perk_name, is_equipped, socket_index)
VALUES (?, ?, ?, ?, ?)
`

type InsertWeaponPerkParams struct {
	InstanceID  string
	PerkHash    int64
	PerkName    string
	IsEquipped  bool
	SocketIndex int64
}

func (q *Queries) InsertWeaponPerk(ctx context.Context, arg InsertWeaponPerkParams) error {
	_, err := q.db.ExecContext(ctx, insertWeaponPerk,
		arg.InstanceID,
		arg.PerkHash,
		arg.PerkName,
		arg.IsEquipped,
		arg.SocketIndex,
	)
	return err
}

const insertWeaponStat = `-- name: InsertWeaponStat :exec
INSERT INTO 
  weapon_stats (instance_id, stat_name, value) VALUES (?, ?, ?)
`

type InsertWeaponStatParams struct {
	InstanceID string
	StatName   string
	Value      int64
}

func (q *Queries) InsertWeaponStat(ctx context.Context, arg InsertWeaponStatParams) error {
	_, err := q.db.ExecContext(ctx, insertWeaponStat, arg.InstanceID, arg.StatName, arg.Value)
	return err
}

const upsertWeapon = `-- name: UpsertWeapon :exec
INSERT INTO 
  weapons (instance_id, hash, name, type, power, kills, level, location, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(instance_id) DO UPDATE SET
    power = excluded.power,
    kills = excluded.kills,
    level = excluded.level,
    location = excluded.location,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertWeaponParams struct {
	InstanceID string
	Hash       int64
	Name       string
	Type       string
	Power      int64
	Kills      int64
	Level      int64
	Location   string
}

func (q *Queries) UpsertWeapon(ctx context.Context, arg UpsertWeaponParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeapon,
		arg.InstanceID,
		arg.Hash,
		arg.Name,
		arg.Type,
		arg.Power,
		arg.Kills,
		arg.Level,
		arg.Location,
	)
	return err
}
